"""update article content type

Revision ID: 762888b7c0ef
Revises: e7e7b1bb30cb
Create Date: 2023-04-23 22:35:46.183661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762888b7c0ef'
down_revision = 'e7e7b1bb30cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'content',
               existing_type=sa.VARCHAR(length=3000),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=3000),
               existing_nullable=False)
    # ### end Alembic commands ###
